### ISSUE TITLE
Issue with uploading image due to size

### ISSUE THREAD

**Issue by NeaGogu** [kdrag0n/fastboot.js#38]
Hello :wave: . I want to flash a device running a custom Android 9 but I am having an issue with one of my image files that is bigger than the `max-download-size` of the device.

- `max-download-size`: 536870912 bytes
- size of `system.img`: 1.8 GB

 I have used the `::flashEntryBlob` function to flash the image, and it attempts to split the sparse image and upload splits individually. It does so correctly until it reaches a **chunk** that is bigger than the `max-download-size`: 537522176 bytes, and the uploading fails with the following error: `FastbootError: Bootloader replied with FAIL: Requested download size is more than max allowed`. From looking at the source code it seems like the scenario where a chunk would not fit in the upload limit is not covered.

I should also mention that using the Fastboot CLI works just fine, so I am assuming it splits the chunk even further. This it the output from fastboot:

```bash
Sending sparse 'system_b' 1/4 (524284 KB)          OKAY [ 16.603s]
Writing 'system_b'                                 OKAY [  0.001s]
Sending sparse 'system_b' 2/4 (524284 KB)          OKAY [ 16.749s]
Writing 'system_b'                                 OKAY [  0.001s]
Sending sparse 'system_b' 3/4 (524284 KB)          OKAY [ 16.449s]
Writing 'system_b'                                 OKAY [  0.001s]
Sending sparse 'system_b' 4/4 (158996 KB)          OKAY [  5.239s]
Writing 'system_b'                                 OKAY [  0.001s]
Finished. Total time: 55.060s
```
 
 I am willing to open a PR on this but I am unsure how to implement this fix. If you could provide some guidance it would be greatly appreciated.

**Comment by NeaGogu** [comment]
These are the logs before the crash

```
Chunk 16: type 51905, 537522176 bytes / 131231 blocks, 269205440 bytes remaining
common.ts:19 Partition is 786432 blocks, used 295102, padded with 491330, finishing split with 786432 blocks
sparse.ts:168 in createImage; buffer is:  ArrayBuffer(28)
common.ts:13 Finished 267665484-byte split with 4 chunks
fastboot.ts:582 split:  {data: ArrayBuffer(267665484), bytes: 770048}
common.ts:13 Uploading single sparse to system_a: 267665484 bytes
common.ts:13 Command: download:0ff4404c
common.ts:13 Response: DATA 0ff4404c
common.ts:13 Sending payload: 267665484 bytes
common.ts:19   Sending 16384 bytes to endpoint, 267665484 remaining, i=0
common.ts:19   Sending 16384 bytes to endpoint, 251281484 remaining, i=1000
common.ts:19   Sending 16384 bytes to endpoint, 234897484 remaining, i=2000
common.ts:19   Sending 16384 bytes to endpoint, 218513484 remaining, i=3000
common.ts:19   Sending 16384 bytes to endpoint, 202129484 remaining, i=4000
common.ts:19   Sending 16384 bytes to endpoint, 185745484 remaining, i=5000
common.ts:19   Sending 16384 bytes to endpoint, 169361484 remaining, i=6000
common.ts:19   Sending 16384 bytes to endpoint, 152977484 remaining, i=7000
common.ts:19   Sending 16384 bytes to endpoint, 136593484 remaining, i=8000
common.ts:19   Sending 16384 bytes to endpoint, 120209484 remaining, i=9000
common.ts:19   Sending 16384 bytes to endpoint, 103825484 remaining, i=10000
common.ts:19   Sending 16384 bytes to endpoint, 87441484 remaining, i=11000
common.ts:19   Sending 16384 bytes to endpoint, 71057484 remaining, i=12000
common.ts:19   Sending 16384 bytes to endpoint, 54673484 remaining, i=13000
common.ts:19   Sending 16384 bytes to endpoint, 38289484 remaining, i=14000
common.ts:19   Sending 16384 bytes to endpoint, 21905484 remaining, i=15000
common.ts:19   Sending 16384 bytes to endpoint, 5521484 remaining, i=16000
common.ts:13 Payload sent, waiting for response...
common.ts:13 Response: OKAY 
common.ts:13 Flashing payload...
common.ts:13 Command: flash:system_a
common.ts:13 Response: OKAY 
common.ts:19 Starting new split: skipping first 295102 blocks and adding chunk
common.ts:19   Chunk 17: type 51907, 0 bytes / 97955 blocks, -651316 bytes remaining
sparse.ts:276       Space is not available, finish this split
splitBlob @ sparse.ts:276
await in splitBlob (async)
flashBlob @ fastboot.ts:581
sparse.ts:277 bytes remaining:  -651316  chunk.dataBytes:  0
splitBlob @ sparse.ts:277
await in splitBlob (async)
flashBlob @ fastboot.ts:581
common.ts:19 Partition is 786432 blocks, used 426333, padded with 360099, finishing split with 786432 blocks
sparse.ts:168 in createImage; buffer is:  ArrayBuffer(28)
common.ts:13 Finished 537522240-byte split with 3 chunks
fastboot.ts:582 split:  {data: ArrayBuffer(537522240), bytes: 0}
common.ts:13 Uploading single sparse to system_a: 537522240 bytes
common.ts:13 Command: download:2009f040
common.ts:13 Response: FAIL Requested download size is more than max allowed

ui.js:51 FastbootError: Bootloader replied with FAIL: Requested download size is more than max allowed

    at FastbootDevice._readResponse (fastboot.ts:312:23)
    at async FastbootDevice.upload (fastboot.ts:469:28)
    at async FastbootDevice.flashBlob (fastboot.ts:584:13)
    at async flashEntryBlob (factory.ts:111:5)
    at async flashArkZip (factory.ts:459:5)
    at async FastbootDevice.flashArkZip (fastboot.ts:645:16)
    at async HTMLFormElement.testFlashArk (ui.js:47:9)
```
